# Generated by Django 5.1.7 on 2025-05-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='receptionist',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'R'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.employee'),
        ),
        migrations.AlterField(
            model_name='roomhygienist',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'type': 'H'}, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.employee'),
        ),
    ]
