# Generated by Django 5.1.7 on 2025-05-12 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books_photo/')),
                ('ISBN', models.CharField(max_length=100)),
                ('year_of_publishing', models.DateField()),
                ('pages', models.IntegerField()),
                ('dimension', models.CharField(max_length=50)),
                ('cover_type', models.CharField(choices=[('H', 'Hard'), ('S', 'Soft')], max_length=1)),
                ('category', models.CharField(choices=[('R', 'Romance'), ('T', 'Thriller'), ('B', 'Biography'), ('C', 'Classic'), ('D', 'Drama'), ('H', 'History')], max_length=1)),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksApp.publishinghouse')),
            ],
        ),
    ]
