# Generated by Django 5.1.7 on 2025-03-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirBalloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
                ('manufacturer', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_founded', models.DateField()),
                ('fliesOutsideEurope', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('total_flight_hours', models.IntegerField()),
                ('position', models.CharField(choices=[('JN', 'Junior'), ('SN', 'Senior'), ('IM', 'Intermediate')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PilotAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airBaloons.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airBaloons.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightCode', models.CharField(max_length=100)),
                ('departureAirport', models.CharField(max_length=100)),
                ('arrivalAirport', models.CharField(max_length=100)),
                ('flightPhoto', models.ImageField(upload_to='flightPhotos')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('airBalloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airBaloons.airballoon')),
                ('flightPilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airBaloons.pilotairline')),
            ],
        ),
    ]
